theme = "dark_plus"

[editor]
line-number = "relative"
cursorline = true
color-modes = true
auto-save = true
bufferline = "multiple"
rulers = [80]

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[keys.normal]
C-j = ["extend_to_line_bounds", "delete_selection", "paste_after"]
C-k = ["extend_to_line_bounds", "delete_selection", "move_line_up","paste_before"]
esc = ["collapse_selection", "keep_primary_selection"]
